name: deploy springboot
on:
  push:
  workflow_dispatch:

jobs:
  deploy-springboot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - name: Build with SpringBoot
        run: mvn -DskipTests package
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          source: "target/demo.jar"
          target: "/tmp/demo.jar"
          overwrite: true
